### PR TITLE
Allow gvcfs from multiple samples with gcoverage

### PR DESCRIPTION
**Pull request by rhpvorderman**
I have completely refactared gcoverage.py and the gcoverage cli.

+ The gcoverage cli now calls one function from gcoverage.py. All logic was moved to gcoverage.py.
+ ~~The at_least_x fields are now calculated using numpy's histogram function which does the same thing. This has the advantage that each coverage and gqarray is only traversed once for all the at_least_x fields instead of once per at_least_x field. In theory this should be computationally more optimal~~ I used the np.greater_equal method instead of our custom at_least method. This is slightly slower because the resulting array needs to be summed. However, reusing existing code from well-maintained libraries that we need to depend on anyway is better than reinventing the wheel. A test was added to make sure this new method worked as expected.
+ The CovStats object no longer performs calculations and is a namedtuple. A tuple can be easily converted to a tsv line so that should speed up things in theory. It now has an instance method (that works from a coverage and genome quality array) that calculates all the stats.
+ Due to using a NamedTuple the column order is now fixed and sane (no at_least_100_dp coming before at_least_10_dp)
+ gcoverage.py is now refactored to be a functional programming library. All functions perform a conversion. There is no state.   CovStats objects are tuples and therefore immutable. Most of the functions are generators.
+ Due to the refactoring it was possible to get the coverage or gq from multiple sample vcfs at once. (NOTE: multiple gvcfs, not multisample GVCF!)
+ Due the refactoring the amount of code lines has decreased by ~40 lines.

Major compatibility breakers:
+ All float fields are now rounded down to only 2 decimals to improve readability. (If the loss of precision is deemed to great this can easily be reverted). Since this is used in our clinical pipeline, this change should be evaluated carefully.
+ The `-I` flag on the command line now does not exist anymore. Instead the GVCFs can be passed without a flag. Multiple GVCFs can be passed now.

Minor issues:
+ Due to using greater_equal + sum it is slightly slower than the custom at_least function, that does not need sum. The difference is only 2% on the total program runtime.

Testing:
+ It outputs the same files as the current release of vtools except for the decimal rounding and the column order. The answers are the same. This was verified manually.
+ Giving the same vcf entry three times yields the same averages medians and at least percentages. As it should. This was also verified manually.

Non-related changes:
- Added a generic python giginore. (From pytest-workflow, but comes originally from https://github.com/github/gitignore)
- Removed requirements.txt. This is already in `install_requires`.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
I refactored the code some more, combining the creation of the coverage and genome quality array. Also the functions determining the coverage and gq per variant have been integrated in this function. This saves ~30 lines of code and removes a lot of code duplication.
Also I have profiled the code to see where the speed difference is from: numpy's histogram algorithm is implemented in python, not in C. So that is where the 10-12% difference in speed comes from as the old algorithm used cython to speed it up. At least gcoverage.py is pure python now, and a 10-12% increase in speed is not worth changing that in my opinion.

**Comment by rhpvorderman** [comment]
I did some digging through the numpy documentation and find a much easier way to count the numbers that are at least x. Even though that requires passing a few times trough the array.

**Comment by rhpvorderman** [comment]
I now did some further optimization using np.bincount. That requires one pass trough the array and returns an array of counts. Using sum on partions of this array is quite quick. 
Since GQ ranges from 0 99. The count array will never be larger than 100 elements. Assuming coverage rarely exceeds 300, the count array will never be larger than 300 elements.  More like 200 ish at most.

Summing the count array will therefore be probably faster than summing an array of booleans coming from the greater_equal function. Especially since only a slice from the count array needs to be summed.

**Review by Redmar-van-den-Berg — APPROVED** [review]
Looks good, using NamedTuple as a base class makes sense if you want to be sure no one can mutate your classes.

**Comment by rhpvorderman** [comment]
It is the functional programming paradigm to work with immutable data. I find this "elimination of state" to work very well indeed. The code becomes easier to read (in my opinion). I also like that every function is a conversion from an immutable data type to another immutable data type. This makes it easier to reason about the flow of data.

**Pull request merged**
